# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy dependency specs
COPY pyproject.toml ./
COPY uv.lock ./

# Install dependencies
RUN pip install --no-cache-dir "mcp[cli]>=1.7.1" httpx

# Copy project files
COPY . .

# Install the project
RUN pip install --no-cache-dir .

# Default command
CMD ["python", "main.py"]
